# Graded: 5 of 5 correct
- [x] Compute the list of all manufacturers whose "Real-World Comb MPG" was higher than 25
- [x] Find the list of all manufacturers whose real-world comb MPG was higher that 25 AND whose 0-60 time is less than 8 seconds
- [x] What was the HP for GM vehicles?
- [x] What were the real-world comb MPG and weight for VW?
- [x] Create a Numpy array that has the real-world comb MPG, weight and 0-60 time (in that order) for Ford, VW and Honda (in that order)

Comments:

## Unit 5 Numpy_Boolean_Selection Quiz
* The objective of this quiz is to understand how to use boolean arrays for selecting subsets from Numpy arrays.

In [1]:
## Import Numpy and check version
import numpy as np
print(f"Numpy version is {np.__version__}")
import pickle
import comp116

Numpy version is 2.1.3

### Boolean arrays are very useful in selecting subsets of arrays.
* Boolean array selection is useful not just for Numpy arays but also Pandas data frames.
* In this quiz you will be working with fuel economy data for selected autmotive vehicle manufacturers for the year 2017.
    * You can get current data similar to this from [here](https://www.fueleconomy.gov/feg/download.shtml).
    * The data you get will need to be cleaned up to get into a format like what we are using in this quiz.
* You will be reading in 3 Numpy arrays, `data_var_names`, `manufacturer_names`, and `mpgData`.
    * `data_var_names` is the array of the type of data that has been read in.
    * `manufacturer_names` is the array of the names of the manufacturer.
    * `mpgData` is the data itself
* You should consider these three arrays as jointly describing a table.
    * `data_var_names` is the first row of the table with headers;
    * `manufacturer_names` is the first column of row labels;
    * `mpgData` is the data itself
    
* When you learn about pandas, you will see that the pandas data frame is an elegant way of keeping these 3 pieces of information in one object, the data frame. For now, we work with numpy arrays.

In [2]:
### Read the pickle file
with open('fuel_economy.data.pickle', 'rb') as fid:
    (data_var_names, manufacturer_names, mpgData) = pickle.load(fid)
comp116.array_to_html(mpgData, row_names=manufacturer_names, col_names=data_var_names,
                      title='2017 Fuel Economy data by Manufacturer')

### For the rest of this quiz, you should use comparisons and boolean values to select subsets. You should not make use of the absolute index of the data.
* For example, you know that `"Real-World Comb MPG"` is in the column with index 0, and `"Ford"` is the row with index 2 in `mpgData`. But do not use `mpgData[2, 0]` to get to the real-world mpg data for Ford. Look at the course lecture on this topic to refresh.

### Compute the list of all manufacturers whose `"Real-World Comb MPG"` was higher than 25.

In [3]:
# Your code here
#following the design pattern for column

#Getting real_world array from the col
real_world_array = data_var_names == "Real-World Comb MPG"
#print("Real_world_array: ",real_world_array)
#offset

#real_word_offset = np.argmax(real_world_array)

#getting the data for the col "Real-World Comb MPG"
real_world_data = mpgData[:,real_world_array]
#print(real_world_data)

#extracting the mask array greater than 25

real_world_data_mask = np.any(real_world_data>25,axis=1)
#print(real_world_data_mask)

#data extraction using mask

real_world = real_world_data[real_world_data_mask,:]
#print(real_world)

#displaying table format
comp116.array_to_html(real_world_data[real_world_data_mask,:], row_names=manufacturer_names[real_world_data_mask],col_names=["Real-World Comb MPG"])

### Find the list of all manufacturers whose real-world comb MPG was higher that 25 AND whose 0-60 time is less than 8 seconds

In [4]:
# Your code here
time_array = data_var_names=="0-60 Time (s)"

time_cnd=mpgData[:,time_array]
# print(time_cnd)
# print(real_world_data)
time_cnd_mask = np.any(time_cnd<8,axis=1)
# print(time_cnd_mask)
# print(real_world_data_mask)

mpg_time_mask  = real_world_data_mask & time_cnd_mask
# print(mpg_time_mask)

mpg_time_array = real_world_array | time_array

mpg_time_data = mpgData[mpg_time_mask,:][:,mpg_time_array]
# print(mpg_time_data)

comp116.array_to_html(mpg_time_data, row_names=manufacturer_names[mpg_time_mask], col_names=data_var_names[mpg_time_array])

### What was the HP for GM vehicles?

In [5]:
# Your code here

gm_array = manufacturer_names =="GM" #row mask
Hp_array = data_var_names == "HP"    #column mask
gm_hp_data = mpgData[gm_array,:][:,Hp_array]   #extracting data
#print(gm_hp_data)

comp116.array_to_html(gm_hp_data,row_names=["GM"],col_names=["HP"])

### What were the real-world comb MPG and weight for VW?

In [6]:
# Your code here

row_mask = manufacturer_names=="VW"

mpg_mask = data_var_names == "Real-World Comb MPG"
weight_mask = data_var_names == "Weight (lbs)"

col_mask = mpg_mask | weight_mask
#print(col_mask)

#extracting data

vw_data = mpgData[row_mask,:][:,col_mask]

comp116.array_to_html(vw_data, row_names=manufacturer_names[row_mask], col_names=data_var_names[col_mask] )

### Create a Numpy array that has the real-world comb MPG, weight and 0-60 time (in that order) for Ford, VW and Honda (in that order)

In [7]:
# Your code here
ford_mask = manufacturer_names=="Ford"
VW_mask = manufacturer_names=="VW"
Honda_mask = manufacturer_names=="Honda"

row_mask1  = ford_mask | VW_mask | Honda_mask
#print(row_mask1)

real_world_mask = data_var_names =="Real-World Comb MPG"
weight_mask = data_var_names=="Weight (lbs)"
time_mask = data_var_names == "0-60 Time (s)"

#col_mask2 = real_world_mask | weight_mask | time_mask
#print(col_mask2)

real_world1 = mpgData[row_mask1,:][:,real_world_mask]
weight1 = mpgData[row_mask1,:][:,weight_mask]
time1 = mpgData[row_mask1,:][:,time_mask]

#to maintain the column order using hstack, which combines the array in exact order
#extracting data

ford_vw_honda = np.hstack([real_world1,weight1,time1])
comp116.array_to_html(ford_vw_honda, row_names=manufacturer_names[row_mask1],col_names=["Real-World Comb MPG","Weight (lbs)","0-60 Time (s)"])