In [39]:
import numpy as np
arr =  np.arange(10)
print("Array range of 10: ",arr)
print("length of an rray range of 10: ",len(arr))
print('arr elements are equal to 5 is', arr == 5)

print('arr elements are greater than 5 is', arr > 5)

print('arr elements are less than 5 is', arr < 5)

print('arr elements are greater than or equal to 5 is', arr >= 5)

print('arr elements are less than or equal to 5 is', arr <= 5)

Array range of 10:  [0 1 2 3 4 5 6 7 8 9]
length of an rray range of 10:  10
arr elements are equal to 5 is [False False False False False  True False False False False]
arr elements are greater than 5 is [False False False False False False  True  True  True  True]
arr elements are less than 5 is [ True  True  True  True  True False False False False False]
arr elements are greater than or equal to 5 is [False False False False False  True  True  True  True  True]
arr elements are less than or equal to 5 is [ True  True  True  True  True  True False False False False]

In [42]:
print('len(arr) is', len(arr), 'and it has shape', arr.shape)
print('The number of elements in arr == 5 is', len(arr == 5), 'and it has shape', (arr == 5).shape)
print('The number of elements in arr != 5 ', len(arr != 5), 'and it has shape', (arr != 5).shape)

print('The number of elements in arr > 5  ', len(arr > 5), 'and it has shape', (arr > 5).shape)

print('The number of elements in arr < 5  ', len(arr < 5), 'and it has shape', (arr < 5).shape)

print('The number of elements in arr >= 5 ', len(arr >= 5), 'and it has shape', (arr >= 5).shape)

print('The number of elements in arr <= 5 ', len(arr <= 5), 'and it has shape', (arr <= 5).shape)

len(arr) is 10 and it has shape (10,)
The number of elements in arr == 5 is 10 and it has shape (10,)
The number of elements in arr != 5  10 and it has shape (10,)
The number of elements in arr > 5   10 and it has shape (10,)
The number of elements in arr < 5   10 and it has shape (10,)
The number of elements in arr >= 5  10 and it has shape (10,)
The number of elements in arr <= 5  10 and it has shape (10,)

In [44]:

import comp116
import pickle

with open("Unit-5-4-Numpy.data.pickle",'rb') as file:
   (state_names, state_co2, co2_categories)= pickle.load(file)

   print(type(state_co2))
   print(type(state_names))
   print(type(co2_categories))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [34]:
comp116.array_to_html(state_co2, row_names=state_names,col_names=co2_categories)

In [49]:
# Design pattern for extracting a row from the file

#finding the idaho in the statename
print(state_names == "Idaho")
Idaho_array = state_names == "Idaho"
Idaho_offset = np.argmax(Idaho_array)
#print(Idaho_offset)

[False False False False  True False False False False False]
4

In [56]:
# extracting the Idaho details from the table
Idaho_details = state_co2[Idaho_offset,:]
print(Idaho_details)
# inorder to avoid the length issue since comp116 accepts only 2D array
print(Idaho_details.shape)
comp116.array_to_html(np.reshape(Idaho_details,(1,len(Idaho_details))),
                      row_names=["Idaho"],col_names=co2_categories)

[ 0.22857  12.298536  5.854803  0.       10.443904  0.315952  0.
  0.        1.253994  0.22857   1.210882  1.929671  0.        0.390809
  0.9755  ]
(15,)

In [68]:
# Design pattern for extracting a column from the file
print("co2_categories in the dataset: ",co2_categories)

nat_gas_array = co2_categories =="Transportation nat gas"
print("Array of nat gas: ",nat_gas_array)

nat_gas_offset = np.argmax(nat_gas_array)
print("Offset of nat gas: ",nat_gas_offset)

nat_gas = state_co2[:,nat_gas_offset]
print(nat_gas)

comp116.array_to_html(np.reshape(nat_gas,(len(nat_gas),1)),row_names=state_names,col_names=["Transportation nat gas"])

co2_categories in the dataset:  ['Total coal' 'Total petro' 'Total nat gas' 'Transportation coal'
 'Transportation petro' 'Transportation nat gas' 'Electrical coal'
 'Electrical petro' 'Electrical nat gas' 'Industrial coal'
 'Industrial petro' 'Industrial nat gas' 'Commercial coal'
 'Commercial petro' 'Commercial nat gas']
Array of nat gas:  [False False False False False  True False False False False False False
 False False False]
Offset of nat gas:  5
[1.037895e+00 4.656780e-01 1.060000e-04 5.038260e-01 3.159520e-01
 1.324931e+00 5.066910e-01 1.079915e+00 5.049930e-01 2.488400e-02]

In [69]:
#multiple rows using boolean rows
#florida or kanasa row selector

#geting florida and kansas mask

florida_mask = state_names=="Florida"
kansas_mask = state_names=="Kansas"

#folorida or kansas evaluator
florida_or_kansas_error = florida_mask or kansas_mask #throw error because wrong operator

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [87]:
#we have to use bitwise operator for element by element boolean comparison
florida_or_kansas_mask = florida_mask | kansas_mask
print("Element by element comparison for florida or kansas: \n", florida_or_kansas_mask)

Element by element comparison for florida or kansas:
 [ True False False False False False False  True False False]

In [79]:
#getting data for florida or kansas
florida_or_kansas = state_co2[florida_or_kansas_mask,:]

comp116.array_to_html(florida_or_kansas, row_names=state_names[florida_or_kansas_mask],col_names=co2_categories)

In [81]:
#  multiple columns using boolean selector
# coal, petrol adn natural gas i.e. the `Ttal coal`, `Total petro` and `Total nat gas` columns

coal_mask = co2_categories=="Total coal"
petrol_mask = co2_categories=="Total petro"
nat_gas_mask = co2_categories=="Total nat gas"

In [85]:
# creating a mask for the col

coal_or_petrol_or_gas_mask = coal_mask|petrol_mask|nat_gas_mask
print("Multiple column mask array: ", coal_or_petrol_or_gas_mask)

Multiple column mask array:  [ True  True  True False False False False False False False False False
 False False False]

In [86]:
#extracting data for the mask

coal_petrol_gas = state_co2[:,coal_or_petrol_or_gas_mask]

comp116.array_to_html(coal_petrol_gas,row_names=state_names,col_names=co2_categories[coal_or_petrol_or_gas_mask])

In [88]:
# can we combine row and column selectors to isolate a subset of the data?
 # we can use florida or kansas mask for row selector
 # Also for column select we can use coal_petrol_gas

#extracting data using the row and col mask

ttotal_co2 = state_co2[florida_or_kansas_mask,:][:,coal_or_petrol_or_gas_mask]

comp116.array_to_html(ttotal_co2,row_names=state_names[florida_or_kansas_mask],col_names=co2_categories[coal_or_petrol_or_gas_mask])

Things to try:
 * Select category names by different names.
 * Select states by comparing names *greater* than something
 * Select $CO_2$ values greater than a certain value using a boolean selector

In [89]:
comp116.array_to_html(state_co2, row_names=state_names,col_names=co2_categories)

In [106]:
#Answer:
# 1. selecting columns to display in the data table
# choosing Electrical coal, Electrical petro and Electrical nat gas
# column masking

elec_coal_mask = co2_categories == "Electrical coal"

elec_petro_mask = co2_categories == "Electrical petro"
elec_nat_gas_mask = co2_categories == "Electrical nat gas"

elec_mask = elec_coal_mask | elec_petro_mask | elec_nat_gas_mask
print("column mask: ",elec_mask)

column mask:  [False False False False False False  True  True  True False False False
 False False False]

In [98]:
#Select states by comparing names *greater* than something
# selecting states >"F"
state_names_lower = np.char.lower(state_names)

row_mask = state_names_lower > "i"
print("row names that starts after F: ",row_mask)

row names that starts after F:  [False False False  True  True  True  True  True  True False]

In [133]:
# 3 .Select $CO_2$ values greater than a certain value using a boolean selector 
# value greater than 1 since the elec petrol value are lesser, we will mask after extracting the data from state co2

df = state_co2[row_mask,:][:,elec_mask]
print(df.shape)

df_mask =np.any(df>1,axis=1)
print(df_mask.shape)

comp116.array_to_html(df[df_mask,:],row_names=state_names[row_mask][df_mask],col_names=co2_categories[elec_mask])

(6, 3)
(6,)