# Graded: 5 of 5 correct
- [x] Display head
- [x] Sort by listed columns
- [x] Set index to listed columns
- [x] Group by `cut` and `clarity` using `mean`
- [x] `VVS1` cross-section

Comments:

In [1]:
import pandas as pd
import seaborn as sns

The next cell loads the `diamonds` dataset from Seaborn

In [2]:
data = sns.load_dataset('diamonds')

Display the first 5 rows of `data`

In [3]:
data.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

Sort `data` by ALL of the columns `cut`, `clarity`, and `color` columns. Then create a MultiIndex by setting the index of `data` to ALL `cut`, `clarity`, and `color`. Display the first 5 rows of `data`.

In [4]:
data = data.sort_values(["cut","clarity","color"])
data = data.set_index(["cut","clarity","color"])
data.head()

                     carat  depth  table  price     x     y     z
cut   clarity color
Ideal IF      D       0.51   62.0   56.0   3446  5.14  5.18  3.20
              D       0.51   62.1   55.0   3446  5.12  5.13  3.19
              D       0.53   61.5   54.0   3517  5.27  5.21  3.22
              D       0.53   62.2   55.0   3812  5.17  5.19  3.22
              D       0.63   61.2   53.0   3832  5.55  5.60  3.41

Group `data` by `cut` and `clarity` using the `mean` function, and save the result as a variable `grouped`. Display `grouped`.

In [5]:
grouped = data.groupby(["cut","clarity"]).mean()
grouped.head()

C:\Users\ramya\AppData\Local\Temp\ipykernel_25532\3902918698.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = data.groupby(["cut","clarity"]).mean()

                  carat      depth      table        price         x  \
cut   clarity
Ideal IF       0.455041  61.645710  55.707013  2272.913366  4.827261
      VVS1     0.495960  61.679091  55.839912  2468.129458  4.960596
      VVS2     0.586213  61.690714  55.915848  3250.290100  5.214693
      VS1      0.674714  61.706436  55.894037  3489.744497  5.449746
      VS2      0.670566  61.730901  55.931256  3284.550385  5.428111

                      y         z
cut   clarity
Ideal IF       4.850289  2.982211
      VVS1     4.978012  3.064304
      VVS2     5.231869  3.221550
      VS1      5.470635  3.366615
      VS2      5.434484  3.352102

Display a cross-section of `grouped` using the `VVS1` clarity.

In [6]:
grouped.xs("VVS1",level="clarity")

,carat,depth,table,price,x,y,z
cut,,,,,,,
Ideal,0.495960,61.679091,55.839912,2468.129458,4.960596,4.978012,3.064304
Premium,0.534821,61.260877,58.674513,2831.206169,5.037955,5.018847,3.080000
Very Good,0.494588,61.675919,57.622687,2459.441065,4.895513,4.927503,3.031420
Good,0.502312,62.123118,58.922581,2254.774194,4.926290,4.950806,3.068602
Fair,0.664706,60.417647,61.235294,3871.352941,5.503529,5.508824,3.327647